spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flat_rent
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
